package config

object EnvVars:
  val SERVER_HOST = "SERVER_HOST"
  val SERVER_PORT = "SERVER_PORT"

  val INVITE_TO_POLL_SUBJECT = "INVITE_TO_POLL_SUBJECT"
  val INVITE_TO_POLL_CONTENT = "INVITE_TO_POLL_CONTENT"

  val GMAIL_USERNAME = "GMAIL_USERNAME"
  val GMAIL_PASSWORD = "GMAIL_PASSWORD"
